DROP PROCEDURE EmplAgeCount;
CREATE PROCEDURE EmplAgeCount (IN age INTEGER, OUT num INTEGER) 
DYNAMIC RESULT SETS 0
LANGUAGE JAVA
EXTERNAL NAME 'DerbyStoredProcedure.countAge'
PARAMETER STYLE JAVA
READS SQL DATA;